kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jenkins-pipeline-bc"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
      env:
        - name: "GUID"
          value: "7cba"
        - name: "REPO"
          value: "https://github.com/mm7259/advdev-homework-trial2.git"
        - name: "CLUSTER"
          value: "master.na311.openshift.opentlc.com"
    type: "JenkinsPipeline"
  source:
    contextDir: "openshift-tasks"
    git: 
      uri: "https://github.com/mm7259/advdev-homework-trial2.git"
      ref: "master"
